# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d904b2d8b3acfb9b30512af9f3c622c3126d262866b0e9e6d8470bf23f5a7f1a3059a780d4a55a20e7c4aa4cede59a5e23e97aea338b28fe4ce997aef67a2506

test:
  secret_key_base: b6caea87b47973f60dc1c42c851d71fb7f1ba8f64c898b5e2b8f9034a23538316e23f8f961c8487a2a9aaa524c9fb354a873ae8c02ed5449a0f76a112efccfb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
